//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coursework2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string NameOfProduct { get; set; }
        public int Price { get; set; }
    }
}
